<?xml version="1.0" encoding="utf-8"?><Database Name="TI2_opdracht2" Class="VerhuurDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOPBEN;Initial Catalog=TI2_opdracht2;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TI2_opdracht2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Vereniging" Member="Verenigings">
    <Type Name="Vereniging">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Naam" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="Vereniging_Persoon" Member="Persoons" ThisKey="Id" OtherKey="VerenigingId" Type="Persoon" />
    </Type>
  </Table>
  <Table Name="dbo.Contract" Member="Contracts">
    <Type Name="Contract">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KampId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PeriodeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Contract_Betaling" Member="Betalings" ThisKey="Id" OtherKey="ContractId" Type="Betaling" />
      <Association Name="Contract_ContractPersoon" Member="ContractPersoons" ThisKey="Id" OtherKey="ContractId" Type="ContractPersoon" />
      <Association Name="Kamp_Contract" Member="Kamp" ThisKey="KampId" OtherKey="Id" Type="Kamp" IsForeignKey="true" />
      <Association Name="Periode_Contract" Member="Periode" ThisKey="PeriodeId" OtherKey="Id" Type="Periode" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kamp" Member="Kamps">
    <Type Name="Kamp">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AantalPersonen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TijdstipAankomst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TijdstipVertrek" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AantalTenten" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Opmerkingen" Type="System.String" DbType="VarChar(5000)" CanBeNull="true" />
      <Column Name="OpkuisVoorafGebeurd" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="OpkuisNadienGebeurd" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Kamp_Contract" Member="Contracts" ThisKey="Id" OtherKey="KampId" Type="Contract" />
    </Type>
  </Table>
  <Table Name="dbo.Type" Member="Types">
    <Type Name="Type">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Naam" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Type_Periode" Member="Periodes" ThisKey="Id" OtherKey="TypeId" Type="Periode" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Naam" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Status_Periode" Member="Periodes" ThisKey="Id" OtherKey="StatusId" Type="Periode" />
    </Type>
  </Table>
  <Table Name="dbo.Periode" Member="Periodes">
    <Type Name="Periode" Id="ID1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BeginPeriode" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EindePeriode" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Periode_Contract" Member="Contracts" ThisKey="Id" OtherKey="PeriodeId" Type="Contract" />
      <Association Name="Status_Periode" Member="Status" ThisKey="StatusId" OtherKey="Id" Type="Status" IsForeignKey="true" />
      <Association Name="Type_Periode" Member="Type" ThisKey="TypeId" OtherKey="Id" Type="Type" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Persoon" Member="Persoons">
    <Type Name="Persoon">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Wachtwoord" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Naam" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Voornaam" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Adres" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Postcode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Plaats" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Telefoonnummer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VerenigingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Persoon_ContractPersoon" Member="ContractPersoons" ThisKey="Id" OtherKey="PersoonId" Type="ContractPersoon" />
      <Association Name="Vereniging_Persoon" Member="Vereniging" ThisKey="VerenigingId" OtherKey="Id" Type="Vereniging" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StatusBetaling" Member="StatusBetalings">
    <Type Name="StatusBetaling">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Naam" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="StatusBetaling_Betaling" Member="Betalings" ThisKey="Id" OtherKey="StatusBetalingId" Type="Betaling" />
    </Type>
  </Table>
  <Table Name="dbo.TypeBetaling" Member="TypeBetalings">
    <Type Name="TypeBetaling">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Naam" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TypeBetaling_Betaling" Member="Betalings" ThisKey="Id" OtherKey="TypeBetalingId" Type="Betaling" />
    </Type>
  </Table>
  <Table Name="dbo.Betaling" Member="Betalings">
    <Type Name="Betaling" Id="ID2">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContractId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Betalingswijze" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TypeBetalingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatusBetalingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bedrag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Contract_Betaling" Member="Contract" ThisKey="ContractId" OtherKey="Id" Type="Contract" IsForeignKey="true" />
      <Association Name="StatusBetaling_Betaling" Member="StatusBetaling" ThisKey="StatusBetalingId" OtherKey="Id" Type="StatusBetaling" IsForeignKey="true" />
      <Association Name="TypeBetaling_Betaling" Member="TypeBetaling" ThisKey="TypeBetalingId" OtherKey="Id" Type="TypeBetaling" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContractPersoon" Member="ContractPersoons">
    <Type Name="ContractPersoon" Id="ID3">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContractId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PersoonId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RolId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Contract_ContractPersoon" Member="Contract" ThisKey="ContractId" OtherKey="Id" Type="Contract" IsForeignKey="true" />
      <Association Name="Persoon_ContractPersoon" Member="Persoon" ThisKey="PersoonId" OtherKey="Id" Type="Persoon" IsForeignKey="true" />
      <Association Name="Rol_ContractPersoon" Member="Rol" ThisKey="RolId" OtherKey="Id" Type="Rol" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rol" Member="Rols">
    <Type Name="Rol">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Naam" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Rol_ContractPersoon" Member="ContractPersoons" ThisKey="Id" OtherKey="RolId" Type="ContractPersoon" />
    </Type>
  </Table>
  <Function Name="dbo.GetPeriodesOpDatum" Method="GetPeriodesOpDatum">
    <Parameter Name="param1" Type="System.DateTime" DbType="Date" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.GetPeriodesTussen" Method="GetPeriodesTussen">
    <Parameter Name="param1" Type="System.DateTime" DbType="Date" />
    <Parameter Name="param2" Type="System.DateTime" DbType="Date" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.GetBetalingenByContractId" Method="GetBetalingenByContractId">
    <Parameter Name="param1" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.GetContractPersonenByContractId" Method="GetContractPersonenByContractId">
    <Parameter Name="param1" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.GetContractPersonenByPersoonId" Method="GetContractPersonenByPersoonId">
    <Parameter Name="param1" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID3" />
  </Function>
</Database>